apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  project: default
  source:
    repoURL: 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/cloud/deploy.yaml'
    path: ''
    targetRevision: HEAD
    helm: {}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
