apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-nginx-ingress
  namespace: ingress-nginx
spec:
  rules:
  - host: ""
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: does-not-matter
            port:
              number: 80
  ingressClassName: nginx
  defaultBackend:
    service:
      name: does-not-matter
      port:
        number: 80
  template:
    metadata:
      annotations:
        nginx.ingress.kubernetes.io/config-map: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: ingress-nginx
data:
  nginx.conf: |
    location = /robots.txt {
      add_header Content-Type text/plain;
      return 200 "User-agent: *\nDisallow: /\n";
    }

    location / {
      add_header Content-Type text/plain;
      return 200 "OK1 \n";
    }
