apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://victoriametrics.github.io/helm-charts/'
    targetRevision: 0.9.15
    chart: victoria-metrics-single
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true